package com.jcourse.zonov.httpserver;

import java.io.*;
import java.net.URLEncoder;
import java.util.List;

public class HtmlBuilder {

    public static StringBuffer toHtmlFile(List<File> list) throws IOException {

        String localDir = list.get(0).getParent();
        System.out.println("localDir: " + localDir);

        String parentDir;
        if (list.get(0).getParentFile().getParent()!=null) {
            parentDir = list.get(0).getParentFile().getParent();
            System.out.println("parentDir: " + parentDir);
        }
        else {
            parentDir = localDir;
        }


        File file = new File(localDir,"index.html");
        StringBuffer sb = new StringBuffer();

//        if (!file.exists()){
//            System.out.println("файла не существует, генерируем");

            try (Writer out = new OutputStreamWriter(new FileOutputStream(file),"UTF-8")) {

                sb.append("<html>" + "\n");
                sb.append("<head>" + "\n");
                sb.append("<title>" + "\n");
                sb.append("HTML autogenerated file" + "\n");
                sb.append("</title>" + "\n");
                sb.append("</head>" + "\n");
                sb.append("<body>" + "\n");

                sb.append("<table border = 0>" + "\n");

                sb.append("<tr>" + "\n");
                sb.append("<td><a href=" +  URLEncoder.encode(parentDir, "UTF-8") + "><b>[Родительский каталог]</b></a></td>" + "\n");
                sb.append("</tr>" + "\n");

                sb.append("<td><b>-----------</b></td>" + "\n");

                sb.append("<tr>" + "\n");
                sb.append("<td><b>[Название]</b></td>" + "\n");
                sb.append("<td><b>[Размер]</b></td>" + "\n");
                sb.append("<td><b>[Дата последнего изменения]</b></td>" + "\n");
                sb.append("</tr>" + "\n");

                for (int i = 0; i < list.size(); i++) {
                    sb.append(HtmlStringBuilder.toHmtlString(list.get(i)) + "\n");
                }

                sb.append("</table>" + "\n");
                sb.append("</body>" + "\n");
                sb.append("</html>" + "\n");
                out.write(sb.toString());
//            sb.setLength(0);

                return sb;
            }

        }
//        else {
//            System.out.println("Файл существует, генерации не будет");
//            return sb.delete(0,sb.length());
//        }
//
//    }

}


